### ISSUE TITLE
When not using a virtual environment, `__COMFY_CLI_SESSION__` will not be set, and `reboot_path` will not be set.

### ISSUE THREAD

**Issue by liusida** [yoland68/comfy-cli#83]
When not using a virtual environment, `__COMFY_CLI_SESSION__` will not be set, and `reboot_path` will not be set.

After setting up a venv, it behaves properly.

My question is, is this the desired behavior? Why does `__COMFY_CLI_SESSION__` related to the functionality of reboot?

Thanks.

**Comment by ltdrdata** [comment]
> __COMFY_CLI_SESSION__

That is to inform that it is being launched from comfy-cli in ComfyUI-Manager.
The default deploy method for ComfyUI on Windows is the run_gpu.bat batch script and python_embedded.

The problem is that the `run_gpu.bat` batch script does not support restarting. Therefore, I have implemented a restart feature using `sys.execv` in ComfyUI-Manager.

However, using `comfy-cli` as the launcher can handle the restart process. The major advantage in this case is that by completely terminating and then restarting the process, it ensures a clean restart by fully releasing VRAM, which is not completely freed when rebooting with `sys.execv`.

**Comment by liusida** [comment]
> What environment are you running? Did you try it with system Python in something like Docker?

Yes, I was on Ubuntu and running a docker container of image `pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime`.

By default, it uses `/opt/conda/python`, and it is None for this line:
https://github.com/yoland68/comfy-cli/blob/78b63fef9b0544254e7f37fc30fe64528f141eac/comfy_cli/cmdline.py#L487

so this line doesn't run:
https://github.com/yoland68/comfy-cli/blob/78b63fef9b0544254e7f37fc30fe64528f141eac/comfy_cli/cmdline.py#L496C17-L496C18

**Comment by ltdrdata** [comment]
> > What environment are you running? Did you try it with system Python in something like Docker?
> 
> Yes, I was on Ubuntu and running a docker container of image `pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime`.
> 
> By default, it uses `/opt/conda/python`, and it is None for this line:
> 
> https://github.com/yoland68/comfy-cli/blob/78b63fef9b0544254e7f37fc30fe64528f141eac/comfy_cli/cmdline.py#L487
> 
> so this line doesn't run:
> 
> https://github.com/yoland68/comfy-cli/blob/78b63fef9b0544254e7f37fc30fe64528f141eac/comfy_cli/cmdline.py#L496

I'll check it.
